#!/usr/bin/env python3
"""
gen_dummy_img.py
================
Generates a minimal Core/Inc/windy_img.h for CI build checks.
No network access required.

The image is a dark-blue gradient that satisfies the C array dimensions
expected by windy_display.c without pulling live weather or map data.

Usage:
    python3 tools/gen_dummy_img.py
"""

import os

WIDTH  = 480
HEIGHT = 272
TOTAL  = WIDTH * HEIGHT

HERE   = os.path.dirname(os.path.abspath(__file__))
OUT    = os.path.join(HERE, "../Core/Inc/windy_img.h")

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

# Dark-blue → slightly lighter gradient, left-to-right
pixels = []
for y in range(HEIGHT):
    for x in range(WIDTH):
        r = 0
        g = (x * 12) // WIDTH          # 0-12 range
        b = 20 + (x * 60) // WIDTH     # 20-80 range
        pixels.append(rgb565(r, g, b))

with open(OUT, "w") as f:
    f.write("/* CI placeholder – generated by tools/gen_dummy_img.py */\n")
    f.write("/* Replace with: python3 tools/windy_render.py            */\n\n")
    f.write("#ifndef WINDY_IMG_H\n#define WINDY_IMG_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define WINDY_IMG_WIDTH  {WIDTH}U\n")
    f.write(f"#define WINDY_IMG_HEIGHT {HEIGHT}U\n\n")
    f.write(f"static const uint16_t windy_img[{TOTAL}U] = {{\n")
    PER_LINE = 16
    for i, px in enumerate(pixels):
        if i % PER_LINE == 0:
            f.write("    ")
        f.write(f"0x{px:04X}")
        if i < TOTAL - 1:
            f.write(",")
        if i % PER_LINE == PER_LINE - 1:
            f.write("\n")
        else:
            f.write(" ")
    if TOTAL % PER_LINE != 0:
        f.write("\n")
    f.write("};\n\n#endif /* WINDY_IMG_H */\n")

print(f"Written {OUT}  ({TOTAL * 2:,} bytes of image data)")
